= Key Map Comparator

== Overview

The motivation behind this API is similar to wanting to compare "prices" from different vendors.
For example, if Tom sells Apples for 2.50 and Bananas for 3.00, but Bob sells Apples for 1.75 and Bananas for 3.25, etc., which is the best deal?
Are there any matches?

KMC summarizes the differences between two key maps, and is intended to be generic.

Row numbers are included to help with cross-references.

== GUI Usage

Run the main method for a simple interface:

....
gui.Index.java
....

There are several example files for testing in

....
src/test/resources
....

== API Usage

Given a set of baseline data:

....
Baseline Row, Baseline Key, Baseline Value
1           , ID_A        , VAL_A
2           , ID_B        , VAL_B
3           , ID_C        , VAL_C
....

and a set external (comparison) data:

....
External Row, External Key, External Value
1           , ID_A        , VAL_A
2           , ID_B        , VAL_C
3           , ID_D        , VAL_E
....

Baseline key-value data matching external key-value data can be logged by rows:

....
Baseline Row, Baseline Key, Baseline Value, External Row, External Key, External Value
1           , ID_A        , VAL_A         , 1           , ID_A        , VAL_A
....

As can all of the key-value data mis-matches:

....
Baseline Row, Baseline Key, Baseline Value, External Row, External Key, External Value
2           , ID_B        , VAL_B         , 2           , ID_B        , VAL_C
3           , ID_C        , VAL_C         , 0           , -           , -
0           , -           , -             , 3           , ID_D        , VAL_E
....

== Notes

See `Makefile` for several useful development commands.

The Baseline and External data are assumed to have unique Keys.

Data mis-matches include scenarios where baseline/external source isn't present.

== Future Development

`findAllMatchesWithAlternates` add alternate detection by flagging a primary column;
to prefer primary data in the case of redundancy

Reporting to generate simple outputs of the matches/differences

Difference matching to include options for inner/outer (inclusive) baseline difference
